---
- name: Get {{ item.name }} status to disable
  become: true
  command: launchctl list {{ item.service }}
  register: status
  changed_when: false
  ignore_errors: true

- name: Stop {{ item.name }} service
  become: true
  command: launchctl unload -w {{ item.plist }}
  when: status.rc == 0
